const quizzes = {
  "py11": {
    "quizId": "py11",
    "title": "1-1. 四則演算",
    "source": "quiz_py",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": false,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "Python講座",
    "description": "",
    "option": ""
  },
  "py12": {
    "quizId": "py12",
    "title": "1-2. 変数と画面出力",
    "source": "quiz_py",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": false,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "Python講座",
    "description": "",
    "option": ""
  },
  "py21": {
    "quizId": "py21",
    "title": "2-1. 条件分岐",
    "source": "quiz_py",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": false,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "Python講座",
    "description": "",
    "option": ""
  },
  "py22a": {
    "quizId": "py22a",
    "title": "2-2. 繰り返し（while文）① A基本問題",
    "source": "quiz_py",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": false,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "Python講座",
    "description": "",
    "option": ""
  },
  "py22b": {
    "quizId": "py22b",
    "title": "2-2. 繰り返し（while文）① B応用問題",
    "source": "quiz_py",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": false,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "Python講座",
    "description": "",
    "option": ""
  },
  "py23a": {
    "quizId": "py23a",
    "title": "2-3. 繰り返し（while文）② A基本問題",
    "source": "quiz_py",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": false,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "Python講座",
    "description": "",
    "option": ""
  },
  "py23b": {
    "quizId": "py23b",
    "title": "2-3. 繰り返し（while文）② B応用問題",
    "source": "quiz_py",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": false,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "Python講座",
    "description": "",
    "option": ""
  },
  "py24a": {
    "quizId": "py24a",
    "title": "2-4. 繰り返し（for文）① A基本問題",
    "source": "quiz_py",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": false,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "Python講座",
    "description": "",
    "option": ""
  },
  "py24b": {
    "quizId": "py24b",
    "title": "2-4. 繰り返し（for文）① B応用問題",
    "source": "quiz_py",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": false,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "Python講座",
    "description": "",
    "option": ""
  },
  "py25a": {
    "quizId": "py25a",
    "title": "2-5. 繰り返し（for文）② A基本問題",
    "source": "quiz_py",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": false,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "Python講座",
    "description": "",
    "option": ""
  },
  "py25b": {
    "quizId": "py25b",
    "title": "2-5. 繰り返し（for文）② B応用問題",
    "source": "quiz_py",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": false,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "Python講座",
    "description": "",
    "option": ""
  },
  "py31a": {
    "quizId": "py31a",
    "title": "3-1. リスト（list） A基本問題",
    "source": "quiz_py",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": false,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "Python講座",
    "description": "",
    "option": ""
  },
  "py31b": {
    "quizId": "py31b",
    "title": "3-1. リスト（list） B応用問題",
    "source": "quiz_py",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": false,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "Python講座",
    "description": "",
    "option": ""
  },
  "py32": {
    "quizId": "py32",
    "title": "3-2. 関数定義（def文）",
    "source": "quiz_py",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": false,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "Python講座",
    "description": "",
    "option": ""
  },
  "ipr01": {
    "quizId": "ipr01",
    "title": "知的財産権と個人情報・プライバシー①",
    "source": "quiz_ipr",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "練習問題",
    "description": "",
    "option": ""
  },
  "ipr02": {
    "quizId": "ipr02",
    "title": "知的財産権と個人情報・プライバシー②",
    "source": "quiz_ipr",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "練習問題",
    "description": "",
    "option": ""
  },
  "ipr03": {
    "quizId": "ipr03",
    "title": "知的財産権と個人情報・プライバシー③",
    "source": "quiz_ipr",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "練習問題",
    "description": "",
    "option": ""
  },
  "lc_test": {
    "quizId": "lc_test",
    "title": "論理回路 テスト",
    "source": "quiz_lc",
    "release": false,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "論理回路",
    "description": "",
    "option": ""
  },
  "lc01": {
    "quizId": "lc01",
    "title": "論理回路①",
    "source": "quiz_lc",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "論理回路",
    "description": "",
    "option": ""
  },
  "lc02": {
    "quizId": "lc02",
    "title": "論理回路②",
    "source": "quiz_lc",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "論理回路",
    "description": "",
    "option": ""
  },
  "lc03": {
    "quizId": "lc03",
    "title": "論理回路③",
    "source": "quiz_lc",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "論理回路",
    "description": "",
    "option": ""
  },
  "lc04": {
    "quizId": "lc04",
    "title": "論理回路④",
    "source": "quiz_lc",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "論理回路",
    "description": "",
    "option": ""
  },
  "lc05": {
    "quizId": "lc05",
    "title": "論理回路⑤",
    "source": "quiz_lc",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "論理回路",
    "description": "",
    "option": ""
  },
  "lc06": {
    "quizId": "lc06",
    "title": "論理回路⑥",
    "source": "quiz_lc",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "論理回路",
    "description": "",
    "option": ""
  },
  "test": {
    "quizId": "test",
    "title": "確認テスト",
    "source": "quiz_test",
    "release": false,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "テスト",
    "description": "",
    "option": ""
  },
  "l11": {
    "quizId": "l11",
    "title": "1-1. 情報とメディア",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l12": {
    "quizId": "l12",
    "title": "1-2. 知的財産権（産業財産権）",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l13": {
    "quizId": "l13",
    "title": "1-3. 知的財産権（著作権）",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l14": {
    "quizId": "l14",
    "title": "1-4. 個人情報の保護と管理",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l15": {
    "quizId": "l15",
    "title": "1-5. 不正アクセス",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l16": {
    "quizId": "l16",
    "title": "1-6. 情報セキュリティ",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l17": {
    "quizId": "l17",
    "title": "1-7. 問題解決の方法",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l18": {
    "quizId": "l18",
    "title": "1-8. 情報技術の進歩",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l19": {
    "quizId": "l19",
    "title": "1-9. 情報技術の進歩による新たな問題",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l21": {
    "quizId": "l21",
    "title": "2-1. コミュニケーション",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l22": {
    "quizId": "l22",
    "title": "2-2. 情報デザイン",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l31": {
    "quizId": "l31",
    "title": "3-1. アナログとデジタル",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l32": {
    "quizId": "l32",
    "title": "3-2. 2進法と16進法",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l33": {
    "quizId": "l33",
    "title": "3-3. 2進法の足し算・引き算",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l34": {
    "quizId": "l34",
    "title": "3-4. 文字のデジタル表現",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l35": {
    "quizId": "l35",
    "title": "3-5. 音のデジタル表現",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l36": {
    "quizId": "l36",
    "title": "3-6. 画像のデジタル表現",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l37": {
    "quizId": "l37",
    "title": "3-7. 動画のデジタル表現",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l38": {
    "quizId": "l38",
    "title": "3-8. データの圧縮",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l41": {
    "quizId": "l41",
    "title": "4-1. コンピュータの構成",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l42": {
    "quizId": "l42",
    "title": "4-2. 論理回路",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l51": {
    "quizId": "l51",
    "title": "5-1. プログラミング",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l52": {
    "quizId": "l52",
    "title": "5-2. アルゴリズム",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l53": {
    "quizId": "l53",
    "title": "5-3. モデル化とシミュレーション",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l61": {
    "quizId": "l61",
    "title": "6-1. 情報通信ネットワークのしくみ",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l62": {
    "quizId": "l62",
    "title": "6-2. プロトコル（第１〜３層）",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l63": {
    "quizId": "l63",
    "title": "6-3. プロトコル（第４層：アプリケーション層）",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l64": {
    "quizId": "l64",
    "title": "6-4. 暗号化のしくみ",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l65": {
    "quizId": "l65",
    "title": "6-5. 情報システム",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l66": {
    "quizId": "l66",
    "title": "6-6. データベース",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l71": {
    "quizId": "l71",
    "title": "7-1. データの収集",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "l72": {
    "quizId": "l72",
    "title": "7-2. データの活用",
    "source": "quiz",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "確認問題",
    "description": "",
    "option": ""
  },
  "bin01": {
    "quizId": "bin01",
    "title": "【練習問題】2進数と10進数",
    "source": "auto",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "換算",
    "description": "",
    "option": "{\"patterns\":[\n  {\"type\":\"bin_dec\",\"count\":2,\"bits\":4},\n  {\"type\":\"dec_bin\",\"count\":2,\"bits\":4},\n  {\"type\":\"bin_dec\",\"count\":2,\"bits\":8},\n  {\"type\":\"dec_bin\",\"count\":2,\"bits\":8}\n]}"
  },
  "hex01": {
    "quizId": "hex01",
    "title": "【練習問題】16進数",
    "source": "auto",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "換算",
    "description": "",
    "option": "{\"patterns\":[\n  {\"type\":\"hex_dec\",\"count\":2},\n  {\"type\":\"dec_hex\",\"count\":2},\n  {\"type\":\"bin_hex\",\"count\":2},\n  {\"type\":\"hex_bin\",\"count\":2}\n]}"
  },
  "realn01": {
    "quizId": "realn01",
    "title": "【練習問題】固定小数点数と浮動小数点数",
    "source": "auto",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "換算",
    "description": "",
    "option": "{\n  \"patterns\":[\n    {\"type\":\"dec_fixedBin\",\"count\":2,\"totalBits\":8,\"fracBits\":4},\n    {\"type\":\"fixedBin_dec\",\"count\":2,\"totalBits\":8,\"fracBits\":4},\n    {\"type\":\"dec_float\",\"count\":2,\"totalBits\":16,\"expBits\":5},\n    {\"type\":\"float_dec\",\"count\":2,\"totalBits\":16,\"expBits\":5}\n  ]\n}"
  },
  "twoscmp01": {
    "quizId": "twoscmp01",
    "title": "【練習問題】補数",
    "source": "auto",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "換算",
    "description": "",
    "option": "{\"patterns\":[\n  {\"type\":\"twos_comp\",\"count\":5, \"bits\": 4},\n  {\"type\":\"twos_comp\",\"count\":5, \"bits\": 8}\n]}"
  },
  "conv01": {
    "quizId": "conv01",
    "title": "換算",
    "source": "auto",
    "release": true,
    "g1": false,
    "g2": false,
    "g3": true,
    "g4": true,
    "g5": true,
    "g6": true,
    "category": "換算",
    "description": "",
    "option": "{\n  \"patterns\":[\n    {\"type\":\"bin_dec\",\"count\":4,\"bits\":8},\n    {\"type\":\"dec_hex\",\"count\":3,\"max\":255},\n    {\"type\":\"twos_comp\",\"count\":2,\"bits\":8},\n    {\"type\":\"dec_fixedBin\",\"count\":1},\n    {\"type\":\"dec_float\",\"count\":5,\"totalBits\":16,\"expBits\":4},\n    {\"type\":\"float_dec\",\"count\":5,\"totalBits\":16,\"expBits\":4}\n  ]\n}"
  }
}