const data = {
  "picto25": {
    "id": "picto25",
    "pid": "picto25",
    "title": "ピクトグラム最終課題",
    "description": "中3 ピクトグラム実習最終課題の提出フォームです。",
    "setId": "picto",
    "grade": 3,
    "perReview": 10,
    "submitStart": "",
    "submitEnd": "",
    "reviewStart": "2025-05-06T15:00:00.000Z",
    "reviewEnd": "2025-07-15T15:00:00.000Z",
    "submitMode": "driveUpload",
    "reviewType": "random",
    "reviewTargetCol": "pngFile",
    "ssId": "15rr-J4rpYZt-iceN4SRtBPJ36E-OfFOOSdV5aoIB214",
    "submitSheet": "submissions",
    "assignSheet": "assignments",
    "statusSheet": "submission_status",
    "ssUrl": "https://docs.google.com/spreadsheets/d/15rr-J4rpYZt-iceN4SRtBPJ36E-OfFOOSdV5aoIB214",
    "url": "https://script.google.com/a/macros/gfe.kaijo.ed.jp/s/AKfycbxBumMkcK31LENmqOX15neY8ZF09nkwD7lIUUzzdhbxtbEt_TYFr_QS32Zs_3Zb6Ba45g/exec?pid=picto25&mode=submit"
  },
  "firefly25": {
    "id": "firefly25",
    "pid": "firefly25",
    "title": "Firefly実習",
    "description": "中3 Firefly実習の提出フォームです。",
    "setId": "firefly",
    "grade": 3,
    "perReview": 10,
    "submitStart": "",
    "submitEnd": "",
    "reviewStart": "",
    "reviewEnd": "",
    "submitMode": "driveUpload",
    "reviewType": "",
    "reviewTargetCol": "pngFile",
    "ssId": "1K1_AtC8vxITB5i83jBEB0v_luC_AV-1dfTQSzS28xSE",
    "submitSheet": "firefly_submit",
    "assignSheet": "",
    "statusSheet": "",
    "ssUrl": "https://docs.google.com/spreadsheets/d/1K1_AtC8vxITB5i83jBEB0v_luC_AV-1dfTQSzS28xSE/edit?gid=0#gid=0",
    "url": "https://script.google.com/a/macros/gfe.kaijo.ed.jp/s/AKfycbxBumMkcK31LENmqOX15neY8ZF09nkwD7lIUUzzdhbxtbEt_TYFr_QS32Zs_3Zb6Ba45g/exec?pid=firefly25&mode=submit"
  },
  "pysmr25": {
    "id": "pysmr25",
    "pid": "pysmr25",
    "title": "Python夏休み自由製作",
    "description": "高1 Python実習 夏休み自由製作の提出フォームです。",
    "setId": "pysmr",
    "grade": 4,
    "perReview": "",
    "submitStart": "",
    "submitEnd": "",
    "reviewStart": "",
    "reviewEnd": "",
    "submitMode": "",
    "reviewType": "",
    "reviewTargetCol": "",
    "ssId": "1OtEbjBkKsUy0thpQFXFvJcPPp2sPLK5WDl-P6KH3cYE",
    "submitSheet": "pysmr25",
    "assignSheet": "",
    "statusSheet": "",
    "ssUrl": "https://docs.google.com/spreadsheets/d/1OtEbjBkKsUy0thpQFXFvJcPPp2sPLK5WDl-P6KH3cYE/edit?gid=0#gid=0",
    "url": "https://script.google.com/a/macros/gfe.kaijo.ed.jp/s/AKfycbxBumMkcK31LENmqOX15neY8ZF09nkwD7lIUUzzdhbxtbEt_TYFr_QS32Zs_3Zb6Ba45g/exec?pid=pysmr25&mode=submit"
  },
  "pysmr25q": {
    "id": "pysmr25q",
    "pid": "pysmr25q",
    "title": "Python夏休み自由製作（グループ内）",
    "description": "",
    "setId": "pysmrq",
    "grade": 4,
    "perReview": 6,
    "submitStart": "",
    "submitEnd": "",
    "reviewStart": "2025-05-05T15:00:00.000Z",
    "reviewEnd": "2025-09-15T15:00:00.000Z",
    "submitMode": "externalUrl",
    "reviewType": "classmate",
    "reviewTargetCol": "",
    "ssId": "1OtEbjBkKsUy0thpQFXFvJcPPp2sPLK5WDl-P6KH3cYE",
    "submitSheet": "",
    "assignSheet": "pysmr25q",
    "statusSheet": "",
    "ssUrl": "https://docs.google.com/spreadsheets/d/1OtEbjBkKsUy0thpQFXFvJcPPp2sPLK5WDl-P6KH3cYE/edit?gid=0#gid=0",
    "url": "https://script.google.com/a/macros/gfe.kaijo.ed.jp/s/AKfycbxBumMkcK31LENmqOX15neY8ZF09nkwD7lIUUzzdhbxtbEt_TYFr_QS32Zs_3Zb6Ba45g/exec?pid=pysmr25q&mode=submit"
  },
  "pysmr25f": {
    "id": "pysmr25f",
    "pid": "pysmr25f",
    "title": "Python夏休み自由製作（全体）",
    "description": "",
    "setId": "pysmrf",
    "grade": 4,
    "perReview": 7,
    "submitStart": "",
    "submitEnd": "",
    "reviewStart": "",
    "reviewEnd": "",
    "submitMode": "",
    "reviewType": "",
    "reviewTargetCol": "",
    "ssId": "1OtEbjBkKsUy0thpQFXFvJcPPp2sPLK5WDl-P6KH3cYE",
    "submitSheet": "",
    "assignSheet": "pysmr25f",
    "statusSheet": "",
    "ssUrl": "https://docs.google.com/spreadsheets/d/1OtEbjBkKsUy0thpQFXFvJcPPp2sPLK5WDl-P6KH3cYE/edit?gid=0#gid=0",
    "url": "https://script.google.com/a/macros/gfe.kaijo.ed.jp/s/AKfycbxBumMkcK31LENmqOX15neY8ZF09nkwD7lIUUzzdhbxtbEt_TYFr_QS32Zs_3Zb6Ba45g/exec?pid=pysmr25f&mode=submit"
  },
  "pywtr25": {
    "id": "pywtr25",
    "pid": "pywtr25",
    "title": "Python冬休み自由製作",
    "description": "高1 Python実習 冬休み自由製作の提出フォームです。",
    "setId": "pywtr",
    "grade": 4,
    "perReview": 7,
    "submitStart": "",
    "submitEnd": "",
    "reviewStart": "",
    "reviewEnd": "",
    "submitMode": "",
    "reviewType": "",
    "reviewTargetCol": "",
    "ssId": "",
    "submitSheet": "",
    "assignSheet": "",
    "statusSheet": "",
    "ssUrl": "",
    "url": "https://script.google.com/a/macros/gfe.kaijo.ed.jp/s/AKfycbxBumMkcK31LENmqOX15neY8ZF09nkwD7lIUUzzdhbxtbEt_TYFr_QS32Zs_3Zb6Ba45g/exec?pid=pywtr25&mode=submit"
  },
  "pywtr25q": {
    "id": "pywtr25q",
    "pid": "pywtr25q",
    "title": "Python冬休み自由製作（グループ内）",
    "description": "",
    "setId": "pywtrq",
    "grade": 4,
    "perReview": 6,
    "submitStart": "",
    "submitEnd": "",
    "reviewStart": "2025-01-07T15:00:00.000Z",
    "reviewEnd": "2025-01-24T15:00:00.000Z",
    "submitMode": "externalUrl",
    "reviewType": "classmate",
    "reviewTargetCol": "",
    "ssId": "",
    "submitSheet": "",
    "assignSheet": "",
    "statusSheet": "",
    "ssUrl": "",
    "url": "https://script.google.com/a/macros/gfe.kaijo.ed.jp/s/AKfycbxBumMkcK31LENmqOX15neY8ZF09nkwD7lIUUzzdhbxtbEt_TYFr_QS32Zs_3Zb6Ba45g/exec?pid=pywtr25q&mode=submit"
  },
  "pywtr25f": {
    "id": "pywtr25f",
    "pid": "pywtr25f",
    "title": "Python冬休み自由製作（全体）",
    "description": "",
    "setId": "pywtrf",
    "grade": 4,
    "perReview": 7,
    "submitStart": "",
    "submitEnd": "",
    "reviewStart": "",
    "reviewEnd": "",
    "submitMode": "",
    "reviewType": "",
    "reviewTargetCol": "",
    "ssId": "",
    "submitSheet": "",
    "assignSheet": "",
    "statusSheet": "",
    "ssUrl": "",
    "url": "https://script.google.com/a/macros/gfe.kaijo.ed.jp/s/AKfycbxBumMkcK31LENmqOX15neY8ZF09nkwD7lIUUzzdhbxtbEt_TYFr_QS32Zs_3Zb6Ba45g/exec?pid=pywtr25f&mode=submit"
  },
  "yuruchara25": {
    "id": "yuruchara25",
    "pid": "yuruchara25",
    "title": "ゆるキャラ製作",
    "description": "中3 夏休み課題「ゆるキャラ製作」の提出フォームです。",
    "setId": "yuruchara",
    "grade": 3,
    "perReview": 8,
    "submitStart": "",
    "submitEnd": "",
    "reviewStart": "2025-09-02T15:00:00.000Z",
    "reviewEnd": "2025-09-22T15:00:00.000Z",
    "submitMode": "driveUpload",
    "reviewType": "random",
    "reviewTargetCol": "pngFile",
    "ssId": "1Y5pix20ApDORGaIi_9L4eVpUCg3WYdWCBz8HUIeulE4",
    "submitSheet": "submissions",
    "assignSheet": "assignments",
    "statusSheet": "submission_status",
    "ssUrl": "https://docs.google.com/spreadsheets/d/1Y5pix20ApDORGaIi_9L4eVpUCg3WYdWCBz8HUIeulE4/edit?gid=0#gid=0",
    "url": "https://script.google.com/a/macros/gfe.kaijo.ed.jp/s/AKfycbxBumMkcK31LENmqOX15neY8ZF09nkwD7lIUUzzdhbxtbEt_TYFr_QS32Zs_3Zb6Ba45g/exec?pid=yuruchara25&mode=submit"
  },
  "test": {
    "id": "test",
    "pid": "test",
    "title": "テスト",
    "description": "テスト",
    "setId": "htmlpractice",
    "grade": 3,
    "perReview": 8,
    "submitStart": "",
    "submitEnd": "",
    "reviewStart": "2025-09-02T15:00:00.000Z",
    "reviewEnd": "2025-09-22T15:00:00.000Z",
    "submitMode": "driveUpload",
    "reviewType": "random",
    "reviewTargetCol": "pngFile",
    "ssId": "1VM7fHFuWjJUb5S24v4QROT3IuQYlIPqbsG-QLWTu1n8",
    "submitSheet": "submissions",
    "assignSheet": "assignments",
    "statusSheet": "submission_status",
    "ssUrl": "https://docs.google.com/spreadsheets/d/1VM7fHFuWjJUb5S24v4QROT3IuQYlIPqbsG-QLWTu1n8/edit?gid=0#gid=0",
    "url": "https://script.google.com/a/macros/gfe.kaijo.ed.jp/s/AKfycbxBumMkcK31LENmqOX15neY8ZF09nkwD7lIUUzzdhbxtbEt_TYFr_QS32Zs_3Zb6Ba45g/exec?pid=test&mode=submit",
    "variants": [
      {
        "variant": "sample1-2",
        "param": "file=sample1-2"
      },
      {
        "variant": "sample1-3_1",
        "param": "file=sample1-3_1"
      },
      {
        "variant": "sample1-3_2",
        "param": "file=sample1-3_2"
      },
      {
        "variant": "sample1-4",
        "param": "file=sample1-4"
      },
      {
        "variant": "sample1-5_1",
        "param": "file=sample1-5_1"
      },
      {
        "variant": "sample1-5_2",
        "param": "file=sample1-5_2"
      },
      {
        "variant": "sample1-6",
        "param": "file=sample1-6"
      },
      {
        "variant": "sample1-7",
        "param": "file=sample1-7"
      },
      {
        "variant": "sample2-2_1",
        "param": "file=sample2-2_1"
      },
      {
        "variant": "sample2-2_2",
        "param": "file=sample2-2_2"
      },
      {
        "variant": "sample2-3",
        "param": "file=sample2-3"
      },
      {
        "variant": "sample2-4",
        "param": "file=sample2-4"
      }
    ]
  }
}